### ISSUE TITLE
Doesn't work with Discord's new 10 MB file size limit

### ISSUE THREAD

**Issue by AdalynBlack** [ScattrdBlade/bigFileUpload#5]
With Discord's new update, adding the """feature""" of reducing the file size limit to 10 MB, it seems that bigFileUpload no longer works. I'm guessing the patches are broken due to code changes to the on-screen modal and upload process

**Comment by ScattrdBlade** [comment]
It seems to work fine on my end. What is the size of the file you tried uploading? Which uploader did you select in settings? Did you try uploading both via the upload button and slash command? What does the error say in the console?

**Comment by AdalynBlack** [comment]
Ah, I see my confusion
There's a separate option for uploading big files, rather than it dynamically using bigFileUpload for big files
It works with the slash command and separate big upload button, but the standard upload button still shows the "File too big modal"
Perhaps there should be a button on that modal to allow you to upload with the plugin? That or a setting to make it dynamically use the big file upload for files that are too big

**Comment by ScattrdBlade** [comment]
A few people have recently brought this up as a suggestion and I might just make it so if the file is more than 10MB then it will default to using the plugin, otherwise, it will use default Discord uploading, or an option that makes the drag and drop option just use the plugin all the time instead of default Discord uploading.
